
package com.barryku.cloud.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.616-07:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "UnexpectedErrorFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class UnexpectedErrorFault_Exception extends Exception {
    
    private com.barryku.cloud.sforce.partner.UnexpectedErrorFault unexpectedErrorFault;

    public UnexpectedErrorFault_Exception() {
        super();
    }
    
    public UnexpectedErrorFault_Exception(String message) {
        super(message);
    }
    
    public UnexpectedErrorFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnexpectedErrorFault_Exception(String message, com.barryku.cloud.sforce.partner.UnexpectedErrorFault unexpectedErrorFault) {
        super(message);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public UnexpectedErrorFault_Exception(String message, com.barryku.cloud.sforce.partner.UnexpectedErrorFault unexpectedErrorFault, Throwable cause) {
        super(message, cause);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public com.barryku.cloud.sforce.partner.UnexpectedErrorFault getFaultInfo() {
        return this.unexpectedErrorFault;
    }
}
